# Java Application

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Java'
    displayName: 'Java Stage'
    jobs:
      - job: 'javaTest'
        displayName: 'Running Test'
        steps:
          - script: echo 'Running Java Test'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'Test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false



  
    
 
