name: findingPR

on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    build: 
        runs-on: ubuntu-latest
        
        steps:              
              - uses: actions/checkout@v1             
                id: find-pull-request
                with:
                    # Can be "open", "closed", or "all".  Defaults to "open".
                  state: open
              - run: echo "Pull Request ${number}"
                env: 
                  number: ${{ steps.find-pull-request.outputs.number }}
            
             
              
    
  
    

