name: findingPR

on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    build: 
        runs-on: ubuntu-latest
        
        steps: 
              - name: Finding Pull Request
                uses: actions/checkout@v1          
                id: findPr
                with:
                 ref: 'Gopinath1906/github-action-demo'
                    # Can be "open", "closed", or "all".  Defaults to "open".
                 state: all
              - run: echo "Your PR is ${PR}"
                if: success() && steps.findPr.outputs.number
                env:
                  PR: ${{ steps.findPr.outputs.pr }}
             
              
    
  
    

