name: findingPR

on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    build: 
        runs-on: ubuntu-latest
        
        steps:  
              - name: Checkout
                uses: actions/checkout@v1 
              - name: npm install and build
                run: |
                    npm ci
                    npm run build
              - name: Finding Pull Request
                uses: ./
                id: findPr
                with:
                    # Can be "open", "closed", or "all".  Defaults to "open".
                  state: all
              - run: echo "Pull Request ${number}"
                env: 
                  number: ${{ steps.findPr.outputs.number }}
            
             
              
    
  
    

