name: findingPR

on:    
  push:
    branches: [ "main" ]

jobs:
    # The type of runner that the job will run on
     build:
   runs-on: ubuntu-latest
       
    steps:
    - name: Run a one-line script
        run: echo Hello, world!
