name: findingPR

on:
  pull_request:
    branches: [ "main" ]

jobs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   steps:
  - name: Find Pull Request
    uses: juliangruber/find-pull-request-action@v1
    id: find-pull-request
    with:
      branch: my-branch-name
  - run: echo "Pull Request ${number} (${sha})"
    env:
      number: ${{ steps.find-pull-request.outputs.number }}
      sha: ${{ steps.find-pull-request.outputs.head-sha }}
