name: findingPR

on:    
  push:
    branches: [ "main" ]
    
jobs:
    build: 
        runs-on: ubuntu-latest
        
        steps:              
              - uses: github-action-demo@v3             
                id: find-pull-request
                with:
                  branch: my-branch-name
              - run: echo "Pull Request ${number} (${sha})"
                env: 
                  number: ${{ steps.find-pull-request.outputs.number }}
                  sha: ${{ steps.find-pull-request.outputs.head-sha }}
             
              
    
  
    

