name: findingPR

on:    
  push:
    branches: [ "main" ]
    
jobs:
    build: 
        runs-on: ubuntu-latest
        
        steps:              
              - uses: actions/checkout@v3
              - name: rune script
              
                run: echo Finding PullRequest
              
              
    
  
    

